apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j3t7i2mmr-java-quarkus
  janus-idp.io/tekton: j3t7i2mmr-java-quarkus
  backstage.io/kubernetes-id: j3t7i2mmr-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j3t7i2mmr-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
